// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateArtistRes interface {
	createArtistRes()
}

type CreateCountryRes interface {
	createCountryRes()
}

type CreateFileRes interface {
	createFileRes()
}

type CreateMovieGenreRes interface {
	createMovieGenreRes()
}

type CreateMovieRes interface {
	createMovieRes()
}

type CreatePictureRes interface {
	createPictureRes()
}

type CreateRatingRes interface {
	createRatingRes()
}

type DeleteArtistRes interface {
	deleteArtistRes()
}

type DeleteCountryRes interface {
	deleteCountryRes()
}

type DeleteFileRes interface {
	deleteFileRes()
}

type DeleteMovieGenreRes interface {
	deleteMovieGenreRes()
}

type DeleteMovieRes interface {
	deleteMovieRes()
}

type DeletePictureRes interface {
	deletePictureRes()
}

type DeleteRatingRes interface {
	deleteRatingRes()
}

type ListArtistActedRes interface {
	listArtistActedRes()
}

type ListArtistCountriesRes interface {
	listArtistCountriesRes()
}

type ListArtistDirectedRes interface {
	listArtistDirectedRes()
}

type ListArtistPicturesRes interface {
	listArtistPicturesRes()
}

type ListArtistRes interface {
	listArtistRes()
}

type ListArtistWroteRes interface {
	listArtistWroteRes()
}

type ListCountryArtistsRes interface {
	listCountryArtistsRes()
}

type ListCountryMoviesRes interface {
	listCountryMoviesRes()
}

type ListCountryRes interface {
	listCountryRes()
}

type ListFileRes interface {
	listFileRes()
}

type ListMovieCastRes interface {
	listMovieCastRes()
}

type ListMovieCountriesRes interface {
	listMovieCountriesRes()
}

type ListMovieDirectorsRes interface {
	listMovieDirectorsRes()
}

type ListMovieFanartRes interface {
	listMovieFanartRes()
}

type ListMovieGenreMoviesRes interface {
	listMovieGenreMoviesRes()
}

type ListMovieGenreRes interface {
	listMovieGenreRes()
}

type ListMovieGenresRes interface {
	listMovieGenresRes()
}

type ListMovieRatingsRes interface {
	listMovieRatingsRes()
}

type ListMovieRes interface {
	listMovieRes()
}

type ListMovieWritersRes interface {
	listMovieWritersRes()
}

type ListPictureRes interface {
	listPictureRes()
}

type ListRatingRes interface {
	listRatingRes()
}

type ReadArtistProfilePictureRes interface {
	readArtistProfilePictureRes()
}

type ReadArtistRes interface {
	readArtistRes()
}

type ReadCountryRes interface {
	readCountryRes()
}

type ReadFileMovieRes interface {
	readFileMovieRes()
}

type ReadFileRes interface {
	readFileRes()
}

type ReadMovieFileRes interface {
	readMovieFileRes()
}

type ReadMovieGenreRes interface {
	readMovieGenreRes()
}

type ReadMoviePosterRes interface {
	readMoviePosterRes()
}

type ReadMovieRes interface {
	readMovieRes()
}

type ReadPictureRes interface {
	readPictureRes()
}

type ReadRatingRes interface {
	readRatingRes()
}

type UpdateArtistRes interface {
	updateArtistRes()
}

type UpdateCountryRes interface {
	updateCountryRes()
}

type UpdateFileRes interface {
	updateFileRes()
}

type UpdateMovieGenreRes interface {
	updateMovieGenreRes()
}

type UpdateMovieRes interface {
	updateMovieRes()
}

type UpdatePictureRes interface {
	updatePictureRes()
}

type UpdateRatingRes interface {
	updateRatingRes()
}
