// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/joelschutz/gomecoma/src/ent/moviegenre"
	"github.com/joelschutz/gomecoma/src/ent/predicate"
)

// MovieGenreDelete is the builder for deleting a MovieGenre entity.
type MovieGenreDelete struct {
	config
	hooks    []Hook
	mutation *MovieGenreMutation
}

// Where appends a list predicates to the MovieGenreDelete builder.
func (mgd *MovieGenreDelete) Where(ps ...predicate.MovieGenre) *MovieGenreDelete {
	mgd.mutation.Where(ps...)
	return mgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mgd *MovieGenreDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mgd.hooks) == 0 {
		affected, err = mgd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MovieGenreMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			mgd.mutation = mutation
			affected, err = mgd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mgd.hooks) - 1; i >= 0; i-- {
			if mgd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mgd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mgd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (mgd *MovieGenreDelete) ExecX(ctx context.Context) int {
	n, err := mgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mgd *MovieGenreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: moviegenre.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: moviegenre.FieldID,
			},
		},
	}
	if ps := mgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mgd.driver, _spec)
}

// MovieGenreDeleteOne is the builder for deleting a single MovieGenre entity.
type MovieGenreDeleteOne struct {
	mgd *MovieGenreDelete
}

// Exec executes the deletion query.
func (mgdo *MovieGenreDeleteOne) Exec(ctx context.Context) error {
	n, err := mgdo.mgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{moviegenre.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mgdo *MovieGenreDeleteOne) ExecX(ctx context.Context) {
	mgdo.mgd.ExecX(ctx)
}
